import {clamp} from '../utils/random.js';
export class FieldRenderer{
  constructor(canvas,settings){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.settings=settings;this.camera={x:0,shake:0};}
  render(game){const c=this.ctx,w=this.canvas.width,h=this.canvas.height;c.imageSmoothingEnabled=false;c.clearRect(0,0,w,h);this.drawStadium(c,w,h,game);c.save();const shake=this.settings.cameraShake?this.camera.shake:0;c.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);this.camera.shake*=.88;this.drawField(c,w,h,game);this.drawEntities(c,game);this.drawBall(c,game);this.drawEffects(c,game);c.restore();}
  drawStadium(c,w,h,game){const grad=c.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#07101b');grad.addColorStop(.32,'#172d42');grad.addColorStop(.33,'#263a47');grad.addColorStop(1,'#07101b');c.fillStyle=grad;c.fillRect(0,0,w,h);for(let row=0;row<5;row++){for(let x=0;x<w;x+=12){const seed=(x*17+row*29+game.frame)%100;c.fillStyle=seed<45?game.homeTeam.primary:seed<70?game.awayTeam.primary:'#cbd5df';c.globalAlpha=.38+row*.05;c.fillRect(x+(row%2)*5,18+row*12,7,6);c.fillRect(x+(row%2)*3,h-72+row*11,7,6)}}c.globalAlpha=1;c.fillStyle='rgba(255,255,255,.08)';c.fillRect(0,76,w,5);c.fillRect(0,h-82,w,5)}
  drawField(c,w,h,game){const top=84,bottom=h-84,left=44,right=w-44;c.fillStyle='#1d6c3c';c.fillRect(left,top,right-left,bottom-top);for(let stripe=0;stripe<10;stripe++){c.fillStyle=stripe%2?'rgba(255,255,255,.035)':'rgba(0,0,0,.035)';c.fillRect(left+stripe*(right-left)/10,top,(right-left)/10,bottom-top)}for(let i=0;i<=10;i++){const x=left+i*(right-left)/10;c.strokeStyle=i===0||i===10?'#f7f7e9':'rgba(255,255,255,.72)';c.lineWidth=i===0||i===10?4:2;c.beginPath();c.moveTo(x,top);c.lineTo(x,bottom);c.stroke();if(i>0&&i<10){c.fillStyle='rgba(255,255,255,.76)';c.font='bold 18px monospace';const n=i<=5?i*10:(10-i)*10;c.fillText(String(n),x-12,top+27);c.save();c.translate(x+12,bottom-27);c.rotate(Math.PI);c.fillText(String(n),0,0);c.restore()}}c.strokeStyle='rgba(255,255,255,.55)';c.lineWidth=2;for(let x=left;x<=right;x+=(right-left)/100){c.beginPath();c.moveTo(x,top+(bottom-top)*.31);c.lineTo(x,top+(bottom-top)*.35);c.moveTo(x,top+(bottom-top)*.65);c.lineTo(x,top+(bottom-top)*.69);c.stroke()}const los=left+game.ballYard/100*(right-left);c.fillStyle='rgba(65,160,255,.45)';c.fillRect(los-2,top,4,bottom-top);const fd=left+clamp(game.ballYard+game.distance,0,100)/100*(right-left);c.fillStyle='rgba(255,220,70,.55)';c.fillRect(fd-2,top,4,bottom-top);c.fillStyle=game.homeTeam.secondary;c.fillRect(left,top,30,bottom-top);c.fillStyle=game.awayTeam.secondary;c.fillRect(right-30,top,30,bottom-top);c.fillStyle='rgba(255,255,255,.8)';c.font='bold 15px monospace';c.fillText(game.homeTeam.abbr,left+3,(top+bottom)/2);c.fillText(game.awayTeam.abbr,right-28,(top+bottom)/2)}
  drawEntities(c,game){for(const e of game.entities){const team=e.side==='offense'?game.offenseTeam:game.defenseTeam;this.drawPlayer(c,e,team,e===game.controlled);}}
  drawPlayer(c,e,team,controlled){const s=e.size||1.05;c.save();c.translate(Math.round(e.x),Math.round(e.y));if(e.dir<0)c.scale(-1,1);c.globalAlpha=.25;c.fillStyle='#000';c.beginPath();c.ellipse(0,12*s,11*s,5*s,0,0,Math.PI*2);c.fill();c.globalAlpha=1;if(controlled){c.strokeStyle='#ffe16d';c.lineWidth=3;c.beginPath();c.arc(0,0,16*s,0,Math.PI*2);c.stroke()}c.fillStyle=team.secondary;c.fillRect(-8*s,-10*s,16*s,18*s);c.fillStyle=team.primary;c.fillRect(-9*s,-7*s,18*s,11*s);c.fillStyle=team.accent;c.fillRect(-9*s,-1*s,18*s,3*s);c.fillStyle=e.skin;c.fillRect(-5*s,-15*s,10*s,6*s);c.fillStyle='#d7e2eb';c.fillRect(-7*s,-19*s,14*s,7*s);c.fillStyle=team.primary;c.fillRect(-8*s,-19*s,16*s,3*s);c.fillStyle='#0c1620';c.fillRect(4*s,-16*s,4*s,2*s);const leg=Math.sin(e.anim)*4*s;c.fillStyle=team.secondary;c.fillRect(-7*s,7*s,5*s,10*s+leg);c.fillRect(2*s,7*s,5*s,10*s-leg);c.fillStyle='#e8edf2';c.fillRect(-8*s,16*s+leg,7*s,3*s);c.fillRect(1*s,16*s-leg,7*s,3*s);c.fillStyle='#fff';c.font=`bold ${7*s}px monospace`;c.textAlign='center';c.fillText(String(e.number||0),0,1*s);c.restore()}
  drawBall(c,game){if(!game.ball.visible)return;c.save();c.translate(game.ball.x,game.ball.y);c.rotate(game.ball.angle);c.fillStyle='#743b1e';c.beginPath();c.ellipse(0,0,8,4,0,0,Math.PI*2);c.fill();c.strokeStyle='#f1e6d0';c.lineWidth=1;c.beginPath();c.moveTo(-2,-3);c.lineTo(2,3);c.stroke();c.restore()}
  drawEffects(c,game){for(const p of game.particles){c.globalAlpha=Math.max(0,p.life);c.fillStyle=p.color;c.fillRect(p.x,p.y,p.size,p.size)}c.globalAlpha=1;if(game.flash>0){c.fillStyle=`rgba(255,255,255,${game.flash})`;c.fillRect(0,0,this.canvas.width,this.canvas.height)}}
  impact(){this.camera.shake=10}
}
