import {InputController} from './inputController.js';
import {FieldRenderer} from './fieldRenderer.js';
import {randomInt,clamp,pick} from '../utils/random.js';
import {timeString} from '../utils/formatting.js';
import {crowdBurst,beep} from '../audio/audioManager.js';
export class GameEngine{
  constructor({canvas,homeTeam,awayTeam,userTeamId,settings,onUpdate,onEnd}){this.canvas=canvas;this.homeTeam=homeTeam;this.awayTeam=awayTeam;this.userTeamId=userTeamId;this.settings=settings;this.onUpdate=onUpdate;this.onEnd=onEnd;this.ctx=canvas.getContext('2d');this.input=new InputController(canvas);this.renderer=new FieldRenderer(canvas,settings);this.width=canvas.width=1280;this.height=canvas.height=720;this.frame=0;this.last=0;this.running=true;this.score={home:0,away:0};this.quarter=1;this.clock=45;this.down=1;this.distance=10;this.ballYard=20;this.possession=homeTeam.id;this.phase='preplay';this.entities=[];this.particles=[];this.flash=0;this.ball={x:0,y:0,visible:false,angle:0};this.message='Choose a play';this.playType=null;this.playTime=0;this.controlled=null;this.offenseTeam=homeTeam;this.defenseTeam=awayTeam;this.stats={home:{yards:0,turnovers:0,passYards:0,rushYards:0},away:{yards:0,turnovers:0,passYards:0,rushYards:0}};this.setupPossession();this.loop=this.loop.bind(this);requestAnimationFrame(this.loop)}
  setupPossession(){this.offenseTeam=this.possession===this.homeTeam.id?this.homeTeam:this.awayTeam;this.defenseTeam=this.possession===this.homeTeam.id?this.awayTeam:this.homeTeam;this.userOnOffense=this.offenseTeam.id===this.userTeamId;this.phase='preplay';this.entities=[];this.ball.visible=false;this.message=this.userOnOffense?'Select offense play':'Select defense play';this.emit()}
  selectPlay(type){if(this.phase!=='preplay'||!this.running)return;if(!this.userOnOffense&&this.settings.defenseMode==='simulate'){this.simulateDefenseDrive();return}if(type==='fieldGoal'){this.kickFieldGoal();return}if(type==='punt'){this.punt();return}this.playType=this.userOnOffense?type:(type==='run'?'run':'pass');this.startPlay()}
  startPlay(){this.phase='live';this.playTime=0;this.message=this.userOnOffense?(this.playType==='run'?'Run the ball':'Move, then press 1/2/3 to pass'):'Track the ball carrier and press Space to tackle';this.spawnFormation();beep(220,.06,.03);this.emit()}
  spawnFormation(){const left=44,right=1236,top=84,bottom=636;const los=left+this.ballYard/100*(right-left);const centerY=(top+bottom)/2;const skins=['#6e432d','#9f6a4b','#d5a17d','#f0c3a1'];this.entities=[];const add=(side,role,x,y,player)=>{const e={side,role,x,y,vx:0,vy:0,dir:1,anim:Math.random()*6,size:role==='OL'||role==='DL'?1.2:1,skin:pick(skins),number:player?.number||randomInt(1,99),rating:player?.overall||65,player};this.entities.push(e);return e};const oRoster=this.offenseTeam.roster,dRoster=this.defenseTeam.roster;const topPlayers=(pos,n,team=oRoster)=>team.filter(p=>p.position===pos).sort((a,b)=>b.overall-a.overall).slice(0,n);const qb=add('offense','QB',los-52,centerY,topPlayers('QB',1)[0]);for(let i=-2;i<=2;i++)add('offense','OL',los-8,centerY+i*35,topPlayers(['OT','OG','C'][Math.abs(i)%3],1)[0]);const rb=add('offense','RB',los-72,centerY+42,topPlayers('RB',1)[0]);const wrs=topPlayers('WR',3);this.receivers=[add('offense','WR',los-5,top+65,wrs[0]),add('offense','WR',los-5,centerY-65,wrs[1]),add('offense','WR',los-5,bottom-65,wrs[2])];for(let i=0;i<7;i++){const pos=i<3?(i%2?'DT':'DE'):i<5?'LB':'CB';const list=topPlayers(pos,3,dRoster);add('defense',pos,los+35+(i>2?55:0),top+80+i*(bottom-top-160)/6,list[i%Math.max(1,list.length)])}this.qb=qb;this.rb=rb;this.ballCarrier=this.playType==='run'?rb:qb;this.controlled=this.userOnOffense?this.ballCarrier:this.entities.filter(e=>e.side==='defense').sort((a,b)=>Math.abs(a.y-centerY)-Math.abs(b.y-centerY))[0];this.ball={x:qb.x+8,y:qb.y,visible:true,angle:0};if(this.playType==='run'){rb.x=qb.x;rb.y=qb.y;this.ballCarrier=rb;this.controlled=this.userOnOffense?rb:this.controlled}}
  loop(t){if(!this.running)return;const dt=Math.min(.034,(t-this.last)/1000||.016);this.last=t;this.update(dt);this.renderer.render(this);requestAnimationFrame(this.loop)}
  update(dt){this.frame++;if(this.phase==='live'){this.clock-=dt;this.playTime+=dt;this.updateEntities(dt);this.updateBall(dt);this.updateParticles(dt);if(this.clock<=0)this.endQuarter()}this.flash=Math.max(0,this.flash-dt*2);this.input.endFrame();if(this.frame%6===0)this.emit()}
  updateEntities(dt){const axis=this.input.axis();const userSpeed=(this.controlled?.rating||70)*.035+2.8;if(this.controlled){this.controlled.vx=axis.x*userSpeed*60;this.controlled.vy=axis.y*userSpeed*60}for(const e of this.entities){if(e===this.controlled){e.x+=e.vx*dt;e.y+=e.vy*dt}else if(e.side==='offense'){if(e.role==='WR'){const lane=this.receivers.indexOf(e);e.vx=85+e.rating*.7;e.vy=Math.sin(this.playTime*1.6+lane)*18}else if(!this.userOnOffense&&e===this.ballCarrier){e.vx=105+e.rating*.75;e.vy=Math.sin(this.playTime*2)*35}else if(e.role==='OL'){e.vx=8}else if(e.role==='RB'&&this.playType==='pass'){e.vx=35}}else{const target=this.ballCarrier||this.ball.flight?.target||this.qb;if(!target)continue;const dx=target.x-e.x,dy=target.y-e.y,l=Math.hypot(dx,dy)||1;const speed=80+e.rating*.8;e.vx=dx/l*speed;e.vy=dy/l*speed}e.x=clamp(e.x+e.vx*dt,45,1235);e.y=clamp(e.y+e.vy*dt,92,628);e.dir=e.vx>=0?1:-1;e.anim+=Math.hypot(e.vx,e.vy)*dt*.08}if(!this.userOnOffense&&this.playType!=='run'&&this.ballCarrier===this.qb&&!this.ball.flight&&this.playTime>1.05)this.throwTo(randomInt(0,2));if(this.userOnOffense&&this.playType==='pass'){if(this.input.consume('Digit1'))this.throwTo(0);if(this.input.consume('Digit2'))this.throwTo(1);if(this.input.consume('Digit3'))this.throwTo(2)}if(!this.userOnOffense&&this.input.consume('Space'))this.attemptTackle();this.checkCollisions();this.checkTouchdown()}
  updateBall(dt){if(this.ball.flight){const f=this.ball.flight;f.t+=dt;const p=clamp(f.t/f.duration,0,1);this.ball.x=f.sx+(f.tx-f.sx)*p;this.ball.y=f.sy+(f.ty-f.sy)*p-Math.sin(p*Math.PI)*50;this.ball.angle+=dt*8;if(p>=1){const target=f.target;const defender=this.nearestDefender(target);const catchChance=.45+(target.rating-60)/90-(defender&&this.distanceBetween(target,defender)<38?.22:0);if(Math.random()<catchChance){this.ballCarrier=target;this.controlled=this.userOnOffense?target:this.controlled;this.ball.flight=null;this.message='Catch! Run!';crowdBurst(1)}else if(defender&&Math.random()<.25){this.turnover('Interception');return}else{this.finishPlay(0,'Incomplete pass');return}}}else if(this.ballCarrier){this.ball.x=this.ballCarrier.x+9;this.ball.y=this.ballCarrier.y-3;this.ball.angle=.2}}
  throwTo(index){if(this.ball.flight||this.ballCarrier!==this.qb)return;const target=this.receivers[index];if(!target)return;const accuracy=(this.qb.player?.attributes?.mediumAccuracy||this.qb.rating)-60;const error=Math.max(2,24-accuracy*.35);this.ball.flight={sx:this.qb.x+8,sy:this.qb.y,tx:target.x+randomInt(-error,error),ty:target.y+randomInt(-error,error),target,t:0,duration:.55+Math.max(0,target.x-this.qb.x)/650};this.ballCarrier=null;this.message=`Pass to receiver ${index+1}`;beep(520,.05,.025)}
  nearestDefender(entity){return this.entities.filter(e=>e.side==='defense').sort((a,b)=>this.distanceBetween(a,entity)-this.distanceBetween(b,entity))[0]}
  distanceBetween(a,b){return Math.hypot(a.x-b.x,a.y-b.y)}
  checkCollisions(){if(!this.ballCarrier)return;for(const d of this.entities.filter(e=>e.side==='defense')){if(this.distanceBetween(d,this.ballCarrier)<17){if(!this.userOnOffense&&d===this.controlled)continue;const tackle=(d.rating+Math.random()*25)>(this.ballCarrier.rating+Math.random()*30);if(tackle){this.renderer.impact();this.spawnParticles(this.ballCarrier.x,this.ballCarrier.y);this.finishPlay(this.yardsFromPosition(),d.role==='DL'?'Tackle for loss':'Tackle');return}}}}
  attemptTackle(){if(!this.controlled||!this.ballCarrier)return;if(this.distanceBetween(this.controlled,this.ballCarrier)<34){const success=(this.controlled.rating+Math.random()*25)>(this.ballCarrier.rating+Math.random()*22);if(success){this.renderer.impact();this.finishPlay(this.yardsFromPosition(),'User tackle')}else this.message='Missed tackle!'}}
  yardsFromPosition(){const left=44,right=1236;const current=(this.ballCarrier?.x??(left+this.ballYard/100*(right-left)))-left;return Math.round(current/(right-left)*100-this.ballYard)}
  checkTouchdown(){if(this.phase==='live'&&this.ballCarrier&&this.ballCarrier.x>=1204){this.phase='result';this.addScore(7);this.message='TOUCHDOWN!';this.flash=.35;crowdBurst(2);this.spawnConfetti();setTimeout(()=>this.afterScore(),700)}}
  finishPlay(yards,label){if(this.phase!=='live')return;this.phase='result';yards=Math.max(-15,Math.min(80,yards));this.ballYard=clamp(this.ballYard+yards,1,99);const statKey=this.possession===this.homeTeam.id?'home':'away';this.stats[statKey].yards+=yards;if(this.playType==='run')this.stats[statKey].rushYards+=yards;else this.stats[statKey].passYards+=Math.max(0,yards);this.distance-=yards;if(this.distance<=0){this.down=1;this.distance=10;this.message=`${label}: ${yards} yards — First down`}else{this.down++;this.message=`${label}: ${yards} yards`;if(this.down>4){this.turnover('Turnover on downs');return}}this.ballYard=Math.min(this.ballYard,99);setTimeout(()=>{if(this.running){this.phase='preplay';this.message=this.userOnOffense?'Choose the next play':'Choose defense';this.emit()}},650);this.emit()}
  turnover(label){const key=this.possession===this.homeTeam.id?'home':'away';this.stats[key].turnovers++;this.possession=this.possession===this.homeTeam.id?this.awayTeam.id:this.homeTeam.id;this.ballYard=clamp(100-this.ballYard,10,90);this.down=1;this.distance=10;this.phase='result';this.message=label;this.renderer.impact();setTimeout(()=>this.setupPossession(),700);this.emit()}

  simulateDefenseDrive(){if(this.phase!=='preplay'||this.userOnOffense)return;this.phase='result';this.message='Simulating defensive possession…';this.emit();setTimeout(()=>{if(!this.running)return;this.clock=Math.max(0,this.clock-randomInt(7,14));const defenseRating=this.defenseTeam.roster.slice().sort((a,b)=>b.overall-a.overall).slice(0,11).reduce((s,p)=>s+p.overall,0)/11;const offenseRating=this.offenseTeam.roster.slice().sort((a,b)=>b.overall-a.overall).slice(0,11).reduce((s,p)=>s+p.overall,0)/11;const roll=Math.random()+(offenseRating-defenseRating)/120;if(roll>.74){this.addScore(7);this.message='Opponent scored a touchdown'}else if(roll>.56){this.addScore(3);this.message='Opponent kicked a field goal'}else this.message='Defense forced a stop';this.possession=this.userTeamId;this.ballYard=25;this.down=1;this.distance=10;if(this.clock<=0)this.endQuarter();else setTimeout(()=>this.setupPossession(),550);this.emit()},650)}
  kickFieldGoal(){const team=this.offenseTeam;const kicker=team.roster.filter(p=>p.position==='K').sort((a,b)=>b.overall-a.overall)[0];const distance=117-this.ballYard;const chance=clamp(.9-(distance-30)*.012+((kicker?.overall||65)-70)*.008,.12,.96);if(Math.random()<chance){this.addScore(3);this.message=`Field goal good from ${distance} yards`;crowdBurst(1)}else this.message='Field goal missed';setTimeout(()=>this.afterScore(),700);this.emit()}
  punt(){this.possession=this.possession===this.homeTeam.id?this.awayTeam.id:this.homeTeam.id;this.ballYard=randomInt(12,28);this.down=1;this.distance=10;this.message='Punt — possession changes';setTimeout(()=>this.setupPossession(),500);this.emit()}
  addScore(points){if(this.possession===this.homeTeam.id)this.score.home+=points;else this.score.away+=points}
  afterScore(){this.possession=this.possession===this.homeTeam.id?this.awayTeam.id:this.homeTeam.id;this.ballYard=25;this.down=1;this.distance=10;this.setupPossession()}
  endQuarter(){this.clock=0;if(this.quarter<4){this.quarter++;this.clock=45;this.phase='result';this.message=`Start of quarter ${this.quarter}`;setTimeout(()=>this.setupPossession(),600)}else this.finishGame()}
  finishGame(){if(this.score.home===this.score.away){this.score.home+=randomInt(0,1)?3:0;this.score.away+=this.score.home===this.score.away?3:0}this.running=false;this.phase='gameover';this.message='Final';this.emit();setTimeout(()=>this.onEnd?.({homeScore:this.score.home,awayScore:this.score.away,stats:this.stats}),400)}
  spawnParticles(x,y){for(let i=0;i<20;i++)this.particles.push({x,y,vx:randomInt(-80,80),vy:randomInt(-80,20),life:1,size:randomInt(2,5),color:i%2?'#8e5d2f':'#4f8a4b'})}
  spawnConfetti(){for(let i=0;i<100;i++)this.particles.push({x:randomInt(0,1280),y:70,vx:randomInt(-20,20),vy:randomInt(20,100),life:2,size:randomInt(2,6),color:pick([this.offenseTeam.primary,this.offenseTeam.accent,'#fff'])})}
  updateParticles(dt){for(const p of this.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=90*dt;p.life-=dt*.7}this.particles=this.particles.filter(p=>p.life>0)}
  emit(){this.onUpdate?.({score:this.score,quarter:this.quarter,clock:timeString(this.clock),down:this.down,distance:this.distance,yard:this.ballYard,phase:this.phase,message:this.message,userOnOffense:this.userOnOffense,offenseTeam:this.offenseTeam,canKick:this.ballYard>=55})}
  setTouchVector(x,y){this.input.setTouchVector(x,y)}
  triggerAction(code){this.input.trigger(code)}
  destroy(){this.running=false;this.input.destroy()}
}
