import {FIRST_NAMES,LAST_NAMES} from '../data/names.js';
import {DEVELOPMENT_TYPES,PERSONALITIES,POSITION_COUNTS} from '../constants.js';
import {pick,randomInt,uid,weightedPick,clamp} from '../utils/random.js';
import {calculateOverall} from './ratingCalculator.js';
const baseKeys=['speed','acceleration','strength','agility','stamina','awareness','balance','reaction','toughness','discipline'];
const posKeys={QB:['shortAccuracy','mediumAccuracy','deepAccuracy','throwPower','decisionMaking','pressureResistance'],RB:['vision','carrying','breakTackle','elusiveness'],FB:['runBlocking','carrying','breakTackle'],WR:['catching','routeRunning','release','contestedCatch'],TE:['catching','routeRunning','runBlocking','passBlocking','contestedCatch'],OT:['passBlocking','runBlocking','technique'],OG:['passBlocking','runBlocking','technique'],C:['passBlocking','runBlocking','technique'],DE:['passRush','blockShedding','tackling','runDefense'],DT:['passRush','blockShedding','tackling','runDefense'],LB:['tackling','zoneCoverage','manCoverage','blockShedding','pursuit'],CB:['manCoverage','zoneCoverage','ballSkills'],S:['zoneCoverage','manCoverage','tackling','ballSkills','pursuit'],K:['kickPower','kickAccuracy','pressure','consistency'],P:['kickPower','kickAccuracy','pressure','consistency']};
function targetRating(){return weightedPick([{value:randomInt(40,49),weight:8},{value:randomInt(50,59),weight:22},{value:randomInt(60,69),weight:32},{value:randomInt(70,79),weight:25},{value:randomInt(80,89),weight:10},{value:randomInt(90,95),weight:2.5},{value:randomInt(96,98),weight:.45},{value:99,weight:.05}]);}
function body(position){const map={QB:[185,104],RB:[179,94],FB:[183,109],WR:[184,91],TE:[194,114],OT:[198,142],OG:[194,139],C:[191,136],DE:[193,122],DT:[190,139],LB:[188,111],CB:[181,88],S:[184,94],K:[183,89],P:[187,92]};const [h,w]=map[position];return{height:h+randomInt(-5,5),weight:w+randomInt(-8,9)};}
export function generatePlayer(position,teamId,age=randomInt(21,34)){const target=targetRating();const attrs={};for(const key of [...baseKeys,...posKeys[position]])attrs[key]=clamp(target+randomInt(-10,10),40,99);if(['WR','CB','RB'].includes(position)){attrs.speed=clamp(target+randomInt(0,10),40,99);attrs.agility=clamp(target+randomInt(-2,9),40,99);}if(['OT','OG','C','DT'].includes(position))attrs.strength=clamp(target+randomInt(1,10),40,99);const overall=calculateOverall(position,attrs);const maxGrowth=Math.max(0,31-age)*1.2;const potential=clamp(Math.round(overall+randomInt(0,Math.max(2,Math.round(maxGrowth+8)))),40,99);const {height,weight}=body(position);return{id:uid('player'),firstName:pick(FIRST_NAMES),lastName:pick(LAST_NAMES),age,birthYear:2026-age,position,secondaryPosition:null,number:randomInt(1,99),height,weight,experience:Math.max(0,age-21),overall,potential,originalPotential:potential,internalCeiling:clamp(potential+randomInt(-4,4),40,99),peakOverall:overall,form:overall,fitness:randomInt(86,100),morale:randomInt(65,92),chemistry:randomInt(55,88),leadership:randomInt(40,99),workEthic:randomInt(40,99),consistency:randomInt(40,99),injuryProneness:randomInt(40,99),personality:pick(PERSONALITIES),developmentType:pick(DEVELOPMENT_TYPES),marketValue:Number((overall/10+Math.max(0,potential-overall)*.22).toFixed(1)),salary:Number(Math.max(.7,(overall-50)*.34+randomInt(0,20)/10).toFixed(1)),signingBonus:Number((Math.max(0,overall-60)*.05).toFixed(1)),contractYears:randomInt(1,4),guaranteed:Number((Math.max(.5,overall-55)*.12).toFixed(1)),role:overall>=82?'Star':overall>=70?'Starter':overall>=60?'Rotation':'Development',playTimeExpectation:overall>=75?'High':'Normal',teamId,injury:null,stats:createStats(),careerStats:createStats(),awards:[],injuryHistory:[],attributes:attrs};}
export function createStats(){return{games:0,passAttempts:0,completions:0,passYards:0,passTD:0,interceptions:0,rushAttempts:0,rushYards:0,rushTD:0,receptions:0,receivingYards:0,receivingTD:0,drops:0,tackles:0,sacks:0,defInterceptions:0,passDeflections:0,forcedFumbles:0,fumbleRecoveries:0,fieldGoalsMade:0,fieldGoalsAttempted:0,puntYards:0,returnYards:0};}
export function generateRoster(teamId){const roster=[];for(const[position,count]of Object.entries(POSITION_COUNTS))for(let i=0;i<count;i++)roster.push(generatePlayer(position,teamId));return roster;}
