import {generateSchedule} from './scheduleGenerator.js';
import {recordGame,sortedStandings} from './standings.js';
import {simulateGame} from '../ai/franchiseAI.js';
import {developRoster} from '../players/development.js';
import {generateDraftClass,runAIDraft} from '../management/draft.js';
import {refreshFreeAgents} from '../management/freeAgency.js';
import {REGULAR_SEASON_WEEKS} from '../config.js';
export function initializeSeason(state){state.schedule=generateSchedule(state.league.teams);state.league.week=1;state.league.phase='regular';}
export function getCurrentGame(state){return state.schedule.find(g=>g.week===state.league.week&&!g.played&&(g.homeTeamId===state.userTeamId||g.awayTeamId===state.userTeamId));}
export function simulateOtherGames(state){for(const game of state.schedule.filter(g=>g.week===state.league.week&&!g.played&&g.homeTeamId!==state.userTeamId&&g.awayTeamId!==state.userTeamId)){const r=simulateGame(state.league,game.homeTeamId,game.awayTeamId);recordGame(state.league,game,r.home,r.away);}}
export function completeUserGame(state,game,home,away,matchStats=null){recordGame(state.league,game,home,away);if(matchStats)applyMatchStats(state,game,matchStats);simulateOtherGames(state);advanceWeek(state);}
function applyMatchStats(state,game,matchStats){for(const [side,teamId] of [['home',game.homeTeamId],['away',game.awayTeamId]]){const team=state.league.teams.find(t=>t.id===teamId);const stats=matchStats[side]||{};const qb=team.roster.filter(p=>p.position==='QB').sort((a,b)=>b.overall-a.overall)[0],rb=team.roster.filter(p=>p.position==='RB').sort((a,b)=>b.overall-a.overall)[0],wr=team.roster.filter(p=>p.position==='WR').sort((a,b)=>b.overall-a.overall)[0],def=team.roster.filter(p=>['LB','S','CB'].includes(p.position)).sort((a,b)=>b.overall-a.overall)[0];for(const p of [qb,rb,wr,def])if(p){p.stats.games++;p.careerStats.games++;}if(qb){qb.stats.passAttempts+=Math.max(5,Math.round((stats.passYards||0)/7));qb.stats.completions+=Math.max(2,Math.round((stats.passYards||0)/11));qb.stats.passYards+=Math.max(0,stats.passYards||0);qb.careerStats.passYards+=Math.max(0,stats.passYards||0);}if(rb){rb.stats.rushAttempts+=Math.max(4,Math.round((stats.rushYards||0)/5));rb.stats.rushYards+=Math.max(0,stats.rushYards||0);rb.careerStats.rushYards+=Math.max(0,stats.rushYards||0);}if(wr){wr.stats.receptions+=Math.max(1,Math.round((stats.passYards||0)/18));wr.stats.receivingYards+=Math.max(0,stats.passYards||0);wr.careerStats.receivingYards+=Math.max(0,stats.passYards||0);}if(def){def.stats.tackles+=randomTackles(stats);def.careerStats.tackles+=randomTackles(stats);}}}
function randomTackles(stats){return Math.max(3,Math.round(5+(stats.yards||0)/45));}
export function advanceWeek(state){if(state.league.week<REGULAR_SEASON_WEEKS){state.league.week++;return;}finishSeason(state);}
function finishSeason(state){const atlantic=sortedStandings(state.league,'Atlantic').slice(0,4),frontier=sortedStandings(state.league,'Frontier').slice(0,4);const finalists=[playBracket(state.league,atlantic),playBracket(state.league,frontier)];const title=simulateGame(state.league,finalists[0].id,finalists[1].id);const champion=title.home>title.away?finalists[0]:finalists[1];champion.history.championships++;state.league.history.push({season:state.league.season,championId:champion.id,standings:state.league.teams.map(t=>({id:t.id,wins:t.wins,losses:t.losses}))});state.league.awards=[{name:'League MVP',playerId:bestPlayer(state.league).id},{name:'Coach of the Year',teamId:sortedStandings(state.league)[0].id}];state.league.phase='offseason';state.draftClass=generateDraftClass(state.league.season+1);refreshFreeAgents(state);}
function playBracket(league,teams){for(const t of teams)t.history.playoffApps++;const a=simulateGame(league,teams[0].id,teams[3].id),b=simulateGame(league,teams[1].id,teams[2].id);const s1=a.home>a.away?teams[0]:teams[3],s2=b.home>b.away?teams[1]:teams[2];const f=simulateGame(league,s1.id,s2.id);return f.home>f.away?s1:s2;}
function bestPlayer(league){return league.teams.flatMap(t=>t.roster).sort((a,b)=>b.overall-a.overall)[0];}
export function startNextSeason(state){runAIDraft(state);for(const t of state.league.teams){developRoster(t,state.trainingFocus,(t.staff.headCoach.development-60)/100);t.wins=t.losses=t.ties=t.pointsFor=t.pointsAgainst=0;}state.league.season++;initializeSeason(state);state.draftClass=[];}
